language: php

git:
  submodules: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - sudo apt-get update -qq
  - git submodule update --init --recursive
  - composer self-update
  - composer install

script:
 - ./vendor/bin/phing -f buildTools/build.xml travis
